name: llm-survival
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - google-api-python-client
  - pip
  - pandas
  - matplotlib
  - seaborn
  - ipython
  - ipykernel
  - jupyter
  - tqdm
  - pip:
    - pip-tools

