name: llm-survival
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python>=3.10,<3.12
  - jupyter
  - pip
  - pip:
    - vllm
    - google-api-python-client
    - pandas
    - matplotlib
    - tqdm
    - numpy
    - detoxify
    - transformers
    - huggingface_hub
    - nltk
    - accelerate
    - lightning