name: llm-survival
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - anaconda::jupyter
  - google-api-python-client
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - numpy
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - detoxify
    - transformers
    - huggingface_hub
    - accelerate

