name: llm-survival
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python >=3.10,<3.12
  - jupyter
  - pip
  - pip:
    - cmake
    - google-api-python-client
    - pandas
    - matplotlib
    - tqdm
    - numpy
    - torch
    - torchvision
    - torchaudio
    - torch-tensorrt
    - detoxify
    - transformers
    - huggingface_hub
    - accelerate

